version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directories:
      - "/.github/build/scripts"
    cooldown:
      default-days: 7
    schedule:
      interval: "daily"
